<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">


    <modelVersion>4.0.0</modelVersion>
    <groupId>com.alrajhi</groupId>
    <artifactId>alrajhi-bom</artifactId>
    <packaging>pom</packaging>
    <version>0.0.1-SNAPSHOT</version>
    <name>Alrajhi Bill of Materials project</name>


    <properties>
        <revision>0.0.1-SNAPSHOT</revision>
        <jasper-version>6.21.0</jasper-version>
        <prometheus-version>1.14.5</prometheus-version>
        <mysql-version>8.2.0</mysql-version>
        <webflux-ui-version>2.8.5</webflux-ui-version>
        <webmvc-ui-version>2.0.2</webmvc-ui-version>
    </properties>


    <dependencyManagement>
       <dependencies>
           <dependency>
               <groupId>org.springframework.boot</groupId>
               <artifactId>spring-boot-devtools</artifactId>
               <scope>runtime</scope>
               <optional>true</optional>
           </dependency>

           <dependency>
               <groupId>com.h2database</groupId>
               <artifactId>h2</artifactId>
               <scope>runtime</scope>
           </dependency>

           <dependency>
               <groupId>org.mapstruct</groupId>
               <artifactId>mapstruct</artifactId>
               <version>1.5.5.Final</version>
           </dependency>

           <dependency>
               <groupId>com.alrajhi</groupId>
               <artifactId>alrajhi-common-lib</artifactId>
               <version>${revision}</version>
           </dependency>

           <dependency>
               <groupId>net.sf.jasperreports</groupId>
               <artifactId>jasperreports</artifactId>
               <version>${jasper-version}</version>
           </dependency>

           <!-- JasperReports Java XML support -->
           <dependency>
               <groupId>net.sf.jasperreports</groupId>
               <artifactId>jasperreports-functions</artifactId>
               <version>${jasper-version}</version>

           </dependency>

           <!-- Font extension (optional, useful for PDF reports) -->
           <dependency>
               <groupId>net.sf.jasperreports</groupId>
               <artifactId>jasperreports-fonts</artifactId>
               <version>${jasper-version}</version>
           </dependency>

           <!-- JavaBeans DataSource -->
           <dependency>
               <groupId>net.sf.jasperreports</groupId>
               <artifactId>jasperreports-javaflow</artifactId>
               <version>${jasper-version}</version>
           </dependency>

           <!-- To enable swagger -->
           <dependency>
               <groupId>org.springdoc</groupId>
               <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
               <version>${webmvc-ui-version}</version>
           </dependency>

           <!-- To enable swagger -->
           <dependency>
               <groupId>org.springdoc</groupId>
               <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
               <version>${webflux-ui-version}</version>
           </dependency>


           <!-- https://mvnrepository.com/artifact/io.micrometer/micrometer-registry-prometheus -->
           <dependency>
               <groupId>io.micrometer</groupId>
               <artifactId>micrometer-registry-prometheus</artifactId>
               <version>${prometheus-version}</version>
           </dependency>

           <dependency>
               <groupId>net.sf.jasperreports</groupId>
               <artifactId>jasperreports-fonts</artifactId>
               <version>${jasper-version}</version>
           </dependency>

           <dependency>
               <groupId>com.mysql</groupId>
               <artifactId>mysql-connector-j</artifactId>
               <version>${mysql-version}</version>
           </dependency>

           <dependency>
               <groupId>com.github.librepdf</groupId>
               <artifactId>openpdf</artifactId>
               <version>1.3.30</version>
           </dependency>

           <dependency>
               <groupId>org.springframework.boot</groupId>
               <artifactId>spring-boot-starter-security</artifactId>
               <version>3.4.5</version> <!-- or latest available -->
           </dependency>

       </dependencies>
    </dependencyManagement>

    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

        <!-- point Nexus repository -->
        <repository>
            <id>nexus-public</id>
            <url>http://localhost:8081/repository/maven-public/</url> <!-- URL for public repository -->
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                        <phase>deploy</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <!-- to deploy on the specific repo -->
    <distributionManagement>
        <repository>
            <id>nexus-releases</id>
            <url>http://localhost:8081/repository/maven-releases/</url> <!-- URL for release repository -->
        </repository>
        <snapshotRepository>
            <id>nexus-snapshots</id>
            <url>http://localhost:8081/repository/maven-snapshots/</url> <!-- URL for snapshot repository -->
        </snapshotRepository>
    </distributionManagement>
</project>