#app:
#  version: @project.version@
#  api:
#    version: 'v1'
#
#info:
#  application:
#    name: '@project.name@'
#    description: '@project.description@'
#    version: '@project.version@'
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: AlRjhi common service

soap:
  urls:
    uploadFile: FileNetUpload