<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>alrajhi-common</artifactId>
        <groupId>com.alrajhi</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <properties>
        <jaxws-api-version>2.3.1</jaxws-api-version>
        <jaxws-maven-version>2.6</jaxws-maven-version>
    </properties>

    <artifactId>alrajhi-soap-lib</artifactId>

    <dependencies>

        <dependency>
            <groupId>javax.xml.ws</groupId>
            <artifactId>jaxws-api</artifactId>
            <version>${jaxws-api-version}</version>
        </dependency>

        <!-- we need it to run the wsdl file after generated -->

        <dependency>
            <groupId>jakarta.jws</groupId>
            <artifactId>jakarta.jws-api</artifactId>
            <version>3.0.0</version>
        </dependency>

        <!-- we need it to run the wsdl file after generated -->

        <dependency>
            <groupId>javax.jws</groupId>
            <artifactId>javax.jws-api</artifactId>
            <version>1.1</version>
        </dependency>

        <!-- we need it to run the wsdl file after generated -->
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
            <version>3.0.1</version>
        </dependency>

        <!-- we need it to run the wsdl file after generated -->
        <!-- JAX-WS Runtime (needed if you call the service at runtime) -->
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-rt</artifactId>
            <version>2.3.3</version>
        </dependency>

        <dependency>
            <groupId>com.alrajhi</groupId>
            <artifactId>alrajhi-common-lib</artifactId>
        </dependency>
    </dependencies>

    <build>
        <!-- Resource tag -->
        <resources>
            <resource>
                <directory>${project.build.directory}/generated-sources/wsdl</directory>
                <includes>
                    <include>**/*.java</include>
                </includes>
            </resource>
        </resources>

        <!-- plugin Tag -->
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/wsdl</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxws-maven-plugin</artifactId>
                <version>${jaxws-maven-version}</version>
                <executions>
                    <execution>
                        <id>generate-sources</id>
                        <goals>
                            <goal>wsimport</goal>
                        </goals>
                        <configuration>
                            <wsdlUrls>
                                <wsdlUrl>${project.basedir}/src/main/resources/wsdl/CommonUtilities.wsdl</wsdlUrl>
                            </wsdlUrls>
                            <packageName>com.alrajhi.client</packageName>
                            <sourceDestDir>${project.build.directory}/generated-sources/wsdl</sourceDestDir>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>