<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.alrajhi</groupId>
		<artifactId>alrajhi-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath/>
	</parent>

	<groupId>com.alrajhi</groupId>
	<artifactId>alrajhi-report</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ReportMicroservice</name>
	<description>Report Microservice</description>

	<dependencies>
		<dependency>
			<groupId>com.alrajhi</groupId>
			<artifactId>alrajhi-common-lib</artifactId>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime </scope>
		</dependency>

		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
		</dependency>

		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
		</dependency>

		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-functions</artifactId>

		</dependency>

		<!-- Font extension (optional, useful for PDF reports) -->
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-fonts</artifactId>
		</dependency>

		<!-- JavaBeans DataSource -->
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-javaflow</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webflux-ui</artifactId>

		</dependency>
	</dependencies>

</project>
