app:
  version: @project.version@
  api:
    version: 'v1'

info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

management:
  info:
    env:
      enabled: true
  endpoints:
    prometheus:
      enable: true
    web:
      base-path: /actuator
      exposure:
        include: '*'


  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  profiles:
    active: dev
  application:
    name: AlRjhi report service

server:
  servlet:
    context-path: /api/v1
  port: 8090

logging:
  level:
    root: INFO
    org.springframework: WARN  # Less detailed logging for Spring